--------------------------------------------------------------------------------------------------------------------------------------------
--   The index is the key you want to recognize, the key is the primary key to press, and the modifier is any modifier needed to be down before you press the key.
--   if you want custom characters, use a forward slash followed by a letter not used. e.i.  "/c" types lctrl
--   currently a single slash is useable with a "//"
--------------------------------------------------------------------------------------------------------------------------------------------
return { --- German Key Layout
   ["/1"] = {mb = 1},
   ["/2"] = {mb = 3},
   ["/3"] = {mb = 2},
   ["/4"] = {mb = 4},
   ["/5"] = {mb = 5},
   ["/6"] = {mb = 6},
   ["/7"] = {mb = 7},

   ["\n"] = {key = 0x28},
   ["\r"] = {key = 0x28},
   ["\t"] = {key = 0x2b},

   ["/a"] = {key = 0xe2},
   ["/A"] = {key = 0xe6},
   ["/c"] = {key = 0xe0},
   ["/C"] = {key = 0xe1},
   ["/s"] = {key = 0xe1},
   ["/S"] = {key = 0xe5},
   ["/w"] = {key = 0xe3},
   ["/W"] = {key = 0xe7},

   ["/l"] = {key = 0x50},
   ["/u"] = {key = 0x51},
   ["/d"] = {key = 0x52},
   ["/r"] = {key = 0x4f},

   ["/e"] = {key = 0x29},
   ["/b"] = {key = 0x2a},
   ["/p"] = {key = 0x46},
   ["/i"] = {key = 0x49},
   ["/h"] = {key = 0x4a},
   ["/m"] = {key = 0x65},
   ["/U"] = {key = 0x4b},
   ["/D"] = {key = 0x4e},
   ["/P"] = {key = 0x48},
   ["/E"] = {key = 0x4d},

   ["/-"] = {key = 0x56},
   ["/+"] = {key = 0x57},
   ["/n"] = {key = 0x58},
   ["/."] = {key = 0x63},

   ["/N"] = {key = 0x53},
   ["/L"] = {key = 0x39},

   ["/01"] = {key = 0x3a},
   ["/02"] = {key = 0x3b},
   ["/03"] = {key = 0x3c},
   ["/04"] = {key = 0x3d},
   ["/05"] = {key = 0x3e},
   ["/06"] = {key = 0x3f},
   ["/07"] = {key = 0x40},
   ["/08"] = {key = 0x41},
   ["/09"] = {key = 0x42},
   ["/10"] = {key = 0x43},
   ["/11"] = {key = 0x44},
   ["/12"] = {key = 0x45},
   ["/13"] = {key = 0x68},
   ["/14"] = {key = 0x69},
   ["/15"] = {key = 0x6a},
   ["/16"] = {key = 0x6b},
   ["/17"] = {key = 0x6c},
   ["/18"] = {key = 0x6d},
   ["/19"] = {key = 0x6e},
   ["/20"] = {key = 0x6f},
   ["/21"] = {key = 0x70},
   ["/22"] = {key = 0x71},
   ["/23"] = {key = 0x72},
   ["/24"] = {key = 0x73},

   ["°"] = {key = 0x32, modifier = "lshift"},
   ["?"] = {key = 0x38, modifier = "lshift"},
   ["`"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x2c}},
   ["Ü"] = {key = 0x2f, modifier = "lshift"},
   ["/*"] = {key = 0x30, modifier = "lshift"},
   ["Ö"] = {key = 0x33, modifier = "lshift"},
   ["Ä"] = {key = 0x34, modifier = "lshift"},
   [";"] = {key = 0x36, modifier = "lshift"},
   [":"] = {key = 0x37, modifier = "lshift"},
   ["_"] = {key = 0x38, modifier = "lshift"},
   [">"] = {key = 0x32, modifier = "lshift"},
   ["'"] = {key = 0x31, modifier = "lshift"},
   ["^"] = {{key = 0x32}, {key = 0x2c}},
   ["ß"] = {key = 0x2d},
   ["´"] = {{key = 0x2e}, {key = 0x2c}},
   ["ü"] = {key = 0x2f},
   ["+"] = {key = 0x30},
   ["ö"] = {key = 0x33},
   ["ä"] = {key = 0x34},
   [","] = {key = 0x36},
   ["."] = {key = 0x37},
   ["-"] = {key = 0x38},
   ["<"] = {key = 0x32},
   ["/#"] = {key = 0x32},
   [" "] = {key = 0x2c},
   ["²"] = {key = 0x1f, modifier = {"lalt", "lctrl"}},
   ["³"] = {key = 0x20, modifier = {"lalt", "lctrl"}},
   ["{"] = {key = 0x24, modifier = {"lalt", "lctrl"}},
   ["["] = {key = 0x25, modifier = {"lalt", "lctrl"}},
   ["]"] = {key = 0x26, modifier = {"lalt", "lctrl"}},
   ["}"] = {key = 0x27, modifier = {"lalt", "lctrl"}},
   ["\\"] = {key = 0x38, modifier = {"lalt", "lctrl"}},
   ["@"] = {key = 0x14, modifier = {"lalt", "lctrl"}},
   ["€"] = {key = 0x08, modifier = {"lalt", "lctrl"}},
   ["/~"] = {key = 0x30, modifier = {"lalt", "lctrl"}},
   ["/|"] = {key = 0x31, modifier = {"lalt", "lctrl"}},
   ["µ"] = {key = 0x10, modifier = {"lalt", "lctrl"}},
   ["!"] = {key = 0x1e, modifier = "lshift"},
   ["\""] = {key = 0x1f, modifier = "lshift"},
   ["§"] = {key = 0x20, modifier = "lshift"},
   ["$"] = {key = 0x21, modifier = "lshift"},
   ["%"] = {key = 0x22, modifier = "lshift"},
   ["&"] = {key = 0x23, modifier = "lshift"},
   ["//"] = {key = 0x24, modifier = "lshift"},
   ["("] = {key = 0x25, modifier = "lshift"},
   [")"] = {key = 0x26, modifier = "lshift"},
   ["="] = {key = 0x27, modifier = "lshift"},

   ["1"] = {key = 0x1e},
   ["2"] = {key = 0x1f},
   ["3"] = {key = 0x20},
   ["4"] = {key = 0x21},
   ["5"] = {key = 0x22},
   ["6"] = {key = 0x23},
   ["7"] = {key = 0x24},
   ["8"] = {key = 0x25},
   ["9"] = {key = 0x26},
   ["0"] = {key = 0x27},

   ["A"] = {key = 0x04, modifier = "lshift"},
   ["B"] = {key = 0x05, modifier = "lshift"},
   ["C"] = {key = 0x06, modifier = "lshift"},
   ["D"] = {key = 0x07, modifier = "lshift"},
   ["E"] = {key = 0x08, modifier = "lshift"},
   ["F"] = {key = 0x09, modifier = "lshift"},
   ["G"] = {key = 0x0a, modifier = "lshift"},
   ["H"] = {key = 0x0b, modifier = "lshift"},
   ["I"] = {key = 0x0c, modifier = "lshift"},
   ["J"] = {key = 0x0d, modifier = "lshift"},
   ["K"] = {key = 0x0e, modifier = "lshift"},
   ["L"] = {key = 0x0f, modifier = "lshift"},
   ["M"] = {key = 0x10, modifier = "lshift"},
   ["N"] = {key = 0x11, modifier = "lshift"},
   ["O"] = {key = 0x12, modifier = "lshift"},
   ["P"] = {key = 0x13, modifier = "lshift"},
   ["Q"] = {key = 0x14, modifier = "lshift"},
   ["R"] = {key = 0x15, modifier = "lshift"},
   ["S"] = {key = 0x16, modifier = "lshift"},
   ["T"] = {key = 0x17, modifier = "lshift"},
   ["U"] = {key = 0x18, modifier = "lshift"},
   ["V"] = {key = 0x19, modifier = "lshift"},
   ["W"] = {key = 0x1a, modifier = "lshift"},
   ["X"] = {key = 0x1b, modifier = "lshift"},
   ["Z"] = {key = 0x1d, modifier = "lshift"},
   ["Y"] = {key = 0x1c, modifier = "lshift"},

   ["a"] = {key = 0x04},
   ["b"] = {key = 0x05},
   ["c"] = {key = 0x06},
   ["d"] = {key = 0x07},
   ["e"] = {key = 0x08},
   ["f"] = {key = 0x09},
   ["g"] = {key = 0x0a},
   ["h"] = {key = 0x0b},
   ["i"] = {key = 0x0c},
   ["j"] = {key = 0x0d},
   ["k"] = {key = 0x0e},
   ["l"] = {key = 0x0f},
   ["m"] = {key = 0x10},
   ["n"] = {key = 0x11},
   ["o"] = {key = 0x12},
   ["p"] = {key = 0x13},
   ["q"] = {key = 0x14},
   ["r"] = {key = 0x15},
   ["s"] = {key = 0x16},
   ["t"] = {key = 0x17},
   ["u"] = {key = 0x18},
   ["v"] = {key = 0x19},
   ["w"] = {key = 0x1a},
   ["x"] = {key = 0x1b},
   ["z"] = {key = 0x1d},
   ["y"] = {key = 0x1c},

   ["Á"] = {{key = 0x2e}, {key = 0x04}},
   ["À"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x04, modifier = "lshift"}},
   ["Â"] = {{key = 0x35}, {key = 0x04}},
   ["É"] = {{key = 0x2e}, {key = 0x08}},
   ["È"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x08, modifier = "lshift"}},
   ["Ê"] = {{key = 0x35}, {key = 0x08}},
   ["Í"] = {{key = 0x2e}, {key = 0x0c}},
   ["Ì"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x0c, modifier = "lshift"}},
   ["Î"] = {{key = 0x35}, {key = 0x0c}},
   ["Ó"] = {{key = 0x2e}, {key = 0x12}},
   ["Ò"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x12, modifier = "lshift"}},
   ["Ô"] = {{key = 0x35}, {key = 0x12}},
   ["Ú"] = {{key = 0x2e}, {key = 0x18}},
   ["Ù"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x18, modifier = "lshift"}},
   ["Û"] = {{key = 0x35}, {key = 0x18}},

   ["á"] = {{key = 0x2e}, {key = 0x04}},
   ["à"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x04}},
   ["â"] = {{key = 0x35}, {key = 0x04}},
   ["é"] = {{key = 0x2e}, {key = 0x08}},
   ["è"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x08}},
   ["ê"] = {{key = 0x35}, {key = 0x08}},
   ["í"] = {{key = 0x2e}, {key = 0x0c}},
   ["ì"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x0c}},
   ["î"] = {{key = 0x35}, {key = 0x0c}},
   ["ó"] = {{key = 0x2e}, {key = 0x12}},
   ["ò"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x12}},
   ["ô"] = {{key = 0x35}, {key = 0x12}},
   ["ú"] = {{key = 0x2e}, {key = 0x18}},
   ["ù"] = {{key = 0x2e, modifier = "lshift"}, {key = 0x18}},
   ["û"] = {{key = 0x35}, {key = 0x18}},

   [""] = {key = ""} -- noop
}