--------------------------------------------------------------------------------------------------------------------------------------------
--   The index is the key you want to recognize, the key is the primary key to press, and the modifier is any modifier needed to be down before you press the key.
--   if you want custom characters, use a forward slash followed by a letter not used. e.i.  "/c" types lctrl
--   currently a single slash is useable with a "//"
--------------------------------------------------------------------------------------------------------------------------------------------
return { --- German Key Layout
   ["/1"] = {mb = 1},
   ["/2"] = {mb = 3},
   ["/3"] = {mb = 2},
   ["/4"] = {mb = 4},
   ["/5"] = {mb = 5},
   ["/6"] = {mb = 6},
   ["/7"] = {mb = 7},

   ["\n"] = {key = 0x28},
   ["\r"] = {key = 0x28},
   ["\t"] = {key = 0x2b},

   ["/a"] = {key = 0xe2},
   ["/A"] = {key = 0xe6},
   ["/c"] = {key = 0xe0},
   ["/C"] = {key = 0xe1},
   ["/s"] = {key = 0xe1},
   ["/S"] = {key = 0xe5},
   ["/w"] = {key = 0xe3},
   ["/W"] = {key = 0xe7},

   ["/l"] = {key = 0x50},
   ["/u"] = {key = 0x51},
   ["/d"] = {key = 0x52},
   ["/r"] = {key = 0x4f},

   ["/e"] = {key = 0x29},
   ["/b"] = {key = 0x2a},
   ["/p"] = {key = 0x46},
   ["/i"] = {key = 0x49},
   ["/h"] = {key = 0x4a},
   ["/m"] = {key = 0x65},
   ["/U"] = {key = 0x4b},
   ["/D"] = {key = 0x4e},
   ["/P"] = {key = 0x48},
   ["/E"] = {key = 0x4d},

   ["/-"] = {key = 0x56},
   ["/+"] = {key = 0x57},
   ["/n"] = {key = 0x58},
   ["/."] = {key = 0x63},

   ["/N"] = {key = 0x53},
   ["/L"] = {key = 0x39},

   ["/01"] = {key = 0x3a},
   ["/02"] = {key = 0x3b},
   ["/03"] = {key = 0x3c},
   ["/04"] = {key = 0x3d},
   ["/05"] = {key = 0x3e},
   ["/06"] = {key = 0x3f},
   ["/07"] = {key = 0x40},
   ["/08"] = {key = 0x41},
   ["/09"] = {key = 0x42},
   ["/10"] = {key = 0x43},
   ["/11"] = {key = 0x44},
   ["/12"] = {key = 0x45},
   ["/13"] = {key = 0x68},
   ["/14"] = {key = 0x69},
   ["/15"] = {key = 0x6a},
   ["/16"] = {key = 0x6b},
   ["/17"] = {key = 0x6c},
   ["/18"] = {key = 0x6d},
   ["/19"] = {key = 0x6e},
   ["/20"] = {key = 0x6f},
   ["/21"] = {key = 0x70},
   ["/22"] = {key = 0x71},
   ["/23"] = {key = 0x72},
   ["/24"] = {key = 0x73},

   ["°"] = {key = "tilde", modifier = "lshift"},
   ["?"] = {key = "minus", modifier = "lshift"},
   ["`"] = {{key = "equal", modifier = "lshift"}, {key = "spacebar"}},
   ["Ü"] = {key = "lbracket", modifier = "lshift"},
   ["/*"] = {key = "rbracket", modifier = "lshift"},
   ["Ö"] = {key = "semicolon", modifier = "lshift"},
   ["Ä"] = {key = "quote", modifier = "lshift"},
   [";"] = {key = "comma", modifier = "lshift"},
   [":"] = {key = "period", modifier = "lshift"},
   ["_"] = {key = "slash", modifier = "lshift"},
   [">"] = {key = "non_us_slash", modifier = "lshift"},
   ["'"] = {key = "backslash", modifier = "lshift"},
   ["^"] = {{key = "tilde"}, {key = "spacebar"}},
   ["ß"] = {key = "minus"},
   ["´"] = {{key = "equal"}, {key = "spacebar"}},
   ["ü"] = {key = "lbracket"},
   ["+"] = {key = "rbracket"},
   ["ö"] = {key = "semicolon"},
   ["ä"] = {key = "quote"},
   [","] = {key = "comma"},
   ["."] = {key = "period"},
   ["-"] = {key = "slash"},
   ["<"] = {key = "non_us_slash"},
   ["/#"] = {key = "backslash"},
   [" "] = {key = "spacebar"},
   ["²"] = {key = "2", modifier = {"lalt", "lctrl"}},
   ["³"] = {key = "3", modifier = {"lalt", "lctrl"}},
   ["{"] = {key = "7", modifier = {"lalt", "lctrl"}},
   ["["] = {key = "8", modifier = {"lalt", "lctrl"}},
   ["]"] = {key = "9", modifier = {"lalt", "lctrl"}},
   ["}"] = {key = "0", modifier = {"lalt", "lctrl"}},
   ["\\"] = {key = "minus", modifier = {"lalt", "lctrl"}},
   ["@"] = {key = "q", modifier = {"lalt", "lctrl"}},
   ["€"] = {key = "e", modifier = {"lalt", "lctrl"}},
   ["/~"] = {key = "rbracket", modifier = {"lalt", "lctrl"}},
   ["/|"] = {key = 86, modifier = {"lalt", "lctrl"}},
   ["µ"] = {key = "m", modifier = {"lalt", "lctrl"}},
   ["!"] = {key = "1", modifier = "lshift"},
   ["\""] = {key = "2", modifier = "lshift"},
   ["§"] = {key = "3", modifier = "lshift"},
   ["$"] = {key = "4", modifier = "lshift"},
   ["%"] = {key = "5", modifier = "lshift"},
   ["&"] = {key = "6", modifier = "lshift"},
   ["//"] = {key = "7", modifier = "lshift"},
   ["("] = {key = "8", modifier = "lshift"},
   [")"] = {key = "9", modifier = "lshift"},
   ["="] = {key = "0", modifier = "lshift"},

   ["1"] = {key = 0x1e},
   ["2"] = {key = 0x1f},
   ["3"] = {key = 0x20},
   ["4"] = {key = 0x21},
   ["5"] = {key = 0x22},
   ["6"] = {key = 0x23},
   ["7"] = {key = 0x24},
   ["8"] = {key = 0x25},
   ["9"] = {key = 0x26},
   ["0"] = {key = 0x27},

   ["A"] = {key = "a", modifier = "lshift"},
   ["B"] = {key = "b", modifier = "lshift"},
   ["C"] = {key = "c", modifier = "lshift"},
   ["D"] = {key = "d", modifier = "lshift"},
   ["E"] = {key = "e", modifier = "lshift"},
   ["F"] = {key = "f", modifier = "lshift"},
   ["G"] = {key = "g", modifier = "lshift"},
   ["H"] = {key = "h", modifier = "lshift"},
   ["I"] = {key = "i", modifier = "lshift"},
   ["J"] = {key = "j", modifier = "lshift"},
   ["K"] = {key = "k", modifier = "lshift"},
   ["L"] = {key = "l", modifier = "lshift"},
   ["M"] = {key = "m", modifier = "lshift"},
   ["N"] = {key = "n", modifier = "lshift"},
   ["O"] = {key = "o", modifier = "lshift"},
   ["P"] = {key = "p", modifier = "lshift"},
   ["Q"] = {key = "q", modifier = "lshift"},
   ["R"] = {key = "r", modifier = "lshift"},
   ["S"] = {key = "s", modifier = "lshift"},
   ["T"] = {key = "t", modifier = "lshift"},
   ["U"] = {key = "u", modifier = "lshift"},
   ["V"] = {key = "v", modifier = "lshift"},
   ["W"] = {key = "w", modifier = "lshift"},
   ["X"] = {key = "x", modifier = "lshift"},
   ["Z"] = {key = "y", modifier = "lshift"},
   ["Y"] = {key = "z", modifier = "lshift"},

   ["a"] = {key = 0x04},
   ["b"] = {key = 0x05},
   ["c"] = {key = 0x06},
   ["d"] = {key = 0x07},
   ["e"] = {key = 0x08},
   ["f"] = {key = 0x09},
   ["g"] = {key = 0x0a},
   ["h"] = {key = 0x0b},
   ["i"] = {key = 0x0c},
   ["j"] = {key = 0x0d},
   ["k"] = {key = 0x0e},
   ["l"] = {key = 0x0f},
   ["m"] = {key = 0x10},
   ["n"] = {key = 0x11},
   ["o"] = {key = 0x12},
   ["p"] = {key = 0x13},
   ["q"] = {key = 0x14},
   ["r"] = {key = 0x15},
   ["s"] = {key = 0x16},
   ["t"] = {key = 0x17},
   ["u"] = {key = 0x18},
   ["v"] = {key = 0x19},
   ["w"] = {key = 0x1a},
   ["x"] = {key = 0x1b},
   ["z"] = {key = 0x1d},
   ["y"] = {key = 0x1c},

   ["Á"] = {{key = 0x2e}, {key = "a"}},
   ["À"] = {{key = 0x2e, modifier = "lshift"}, {key = "a", modifier = "lshift"}},
   ["Â"] = {{key = "tilde"}, {key = "a"}},
   ["É"] = {{key = 0x2e}, {key = "e"}},
   ["È"] = {{key = "equal", modifier = "lshift"}, {key = "e", modifier = "lshift"}},
   ["Ê"] = {{key = "tilde"}, {key = "e"}},
   ["Í"] = {{key = "equal"}, {key = "i"}},
   ["Ì"] = {{key = "equal", modifier = "lshift"}, {key = "i", modifier = "lshift"}},
   ["Î"] = {{key = "tilde"}, {key = "i"}},
   ["Ó"] = {{key = "equal"}, {key = "o"}},
   ["Ò"] = {{key = "equal", modifier = "lshift"}, {key = "o", modifier = "lshift"}},
   ["Ô"] = {{key = "tilde"}, {key = "o"}},
   ["Ú"] = {{key = "equal"}, {key = "u"}},
   ["Ù"] = {{key = "equal", modifier = "lshift"}, {key = "u", modifier = "lshift"}},
   ["Û"] = {{key = "tilde"}, {key = "u"}},

   ["á"] = {{key = 0x2e}, {key = "a"}},
   ["à"] = {{key = 0x2e, modifier = "lshift"}, {key = "a"}},
   ["â"] = {{key = "tilde"}, {key = "a"}},
   ["é"] = {{key = 0x2e}, {key = "e"}},
   ["è"] = {{key = 0x2e, modifier = "lshift"}, {key = "e"}},
   ["ê"] = {{key = "tilde"}, {key = "e"}},
   ["í"] = {{key = "equal"}, {key = "i"}},
   ["ì"] = {{key = "equal", modifier = "lshift"}, {key = "i"}},
   ["î"] = {{key = "tilde"}, {key = "i"}},
   ["ó"] = {{key = "equal"}, {key = "o"}},
   ["ò"] = {{key = "equal", modifier = "lshift"}, {key = "o"}},
   ["ô"] = {{key = "tilde"}, {key = "o"}},
   ["ú"] = {{key = "equal"}, {key = "u"}},
   ["ù"] = {{key = "equal", modifier = "lshift"}, {key = "u"}},
   ["û"] = {{key = "tilde"}, {key = "u"}},

   [""] = {key = ""} -- noop
}