--------------------------------------------------------------------------------------------------------------------------------------------
--	The index is the key you want to recognize, the key is the primary key to press, and the modifier is any modifier needed to be down before you press the key.
--	if you want custom characters, use a forward slash followed by a letter not used. e.i.  "/c" types lctrl
--	currently a single slash is useable with a "//"
--------------------------------------------------------------------------------------------------------------------------------------------
return { --- American Key Layout
   ["/1"] = {mb = 1},
   ["/2"] = {mb = 3},
   ["/3"] = {mb = 2},
   ["/4"] = {mb = 4},
   ["/5"] = {mb = 5},
   ["/6"] = {mb = 6},
   ["/7"] = {mb = 7},

   ["\n"] = {key = 0x28},
   ["\r"] = {key = 0x28},
   ["enter"] = {key = 0x28},
   ["\t"] = {key = 0x2b},
   ["tab"] = {key = 0x2b},

   ["/a"] = {key = 0xe2},
   ["lalt"] = {key = 0xe2},
   ["/A"] = {key = 0xe6},
   ["ralt"] = {key = 0xe6},
   ["/c"] = {key = 0xe0},
   ["lctrl"] = {key = 0xe0},
   ["/C"] = {key = 0xe1},
   ["rctrl"] = {key = 0xe1},
   ["/s"] = {key = 0xe1},
   ["lshift"] = {key = 0xe1},
   ["/S"] = {key = 0xe5},
   ["rshift"] = {key = 0xe5},
   ["/w"] = {key = 0xe3},
   ["lgui"] = {key = 0xe3},
   ["/W"] = {key = 0xe7},
   ["rgui"] = {key = 0xe7},

   ["/l"] = {key = 0x50},
   ["left"] = {key = 0x50},
   ["/u"] = {key = 0x51},
   ["up"] = {key = 0x51},
   ["/d"] = {key = 0x52},
   ["down"] = {key = 0x52},
   ["/r"] = {key = 0x4f},
   ["right"] = {key = 0x4f},

   ["/e"] = {key = 0x29},
   ["escape"] = {key = 0x29},
   ["/b"] = {key = 0x2a},
   ["backspace"] = {key = 0x2a},
   ["/p"] = {key = 0x46},
   ["printscreen"] = {key = 0x46},
   ["/i"] = {key = 0x49},
   ["insert"] = {key = 0x49},
   ["/h"] = {key = 0x4a},
   ["home"] = {key = 0x4a},
   ["/m"] = {key = 0x65},
   ["appkey"] = {key = 0x65},
   ["/U"] = {key = 0x4b},
   ["pageup"] = {key = 0x4b},
   ["/D"] = {key = 0x4e},
   ["pagedown"] = {key = 0x4e},
   ["/P"] = {key = 0x48},
   ["pause"] = {key = 0x48},
   ["/E"] = {key = 0x4d},
   ["end"] = {key = 0x4d},

   ["numslash"] = {key = 0x54},
   ["num1"] = {key = 0x59},
   ["num2"] = {key = 0x5a},
   ["num3"] = {key = 0x5b},
   ["num4"] = {key = 0x5c},
   ["num5"] = {key = 0x5d},
   ["num6"] = {key = 0x5e},
   ["num7"] = {key = 0x5f},
   ["num8"] = {key = 0x60},
   ["num9"] = {key = 0x61},
   ["num0"] = {key = 0x62},

   ["/-"] = {key = 0x56},
   ["numminus"] = {key = 0x56},
   ["/+"] = {key = 0x57},
   ["numplus"] = {key = 0x57},
   ["/n"] = {key = 0x58},
   ["numenter"] = {key = 0x58},
   ["/."] = {key = 0x63},
   ["numperiod"] = {key = 0x63},

   ["/N"] = {key = 0x53},
   ["numlock"] = {key = 0x53},
   ["/L"] = {key = 0x39},
   ["capslock"] = {key = 0x39},

   ["/01"] = {key = 0x3a},
   ["f1"] = {key = 0x3a},
   ["/02"] = {key = 0x3b},
   ["f2"] = {key = 0x3b},
   ["/03"] = {key = 0x3c},
   ["f3"] = {key = 0x3c},
   ["/04"] = {key = 0x3d},
   ["f4"] = {key = 0x3d},
   ["/05"] = {key = 0x3e},
   ["f5"] = {key = 0x3e},
   ["/06"] = {key = 0x3f},
   ["f6"] = {key = 0x3f},
   ["/07"] = {key = 0x40},
   ["f7"] = {key = 0x40},
   ["/08"] = {key = 0x41},
   ["f8"] = {key = 0x41},
   ["/09"] = {key = 0x42},
   ["f9"] = {key = 0x42},
   ["/10"] = {key = 0x43},
   ["f10"] = {key = 0x43},
   ["/11"] = {key = 0x44},
   ["f11"] = {key = 0x44},
   ["/12"] = {key = 0x45},
   ["f12"] = {key = 0x45},
   ["/13"] = {key = 0x68},
   ["f13"] = {key = 0x68},
   ["/14"] = {key = 0x69},
   ["f14"] = {key = 0x69},
   ["/15"] = {key = 0x6a},
   ["f15"] = {key = 0x6a},
   ["/16"] = {key = 0x6b},
   ["f16"] = {key = 0x6b},
   ["/17"] = {key = 0x6c},
   ["f17"] = {key = 0x6c},
   ["/18"] = {key = 0x6d},
   ["f18"] = {key = 0x6d},
   ["/19"] = {key = 0x6e},
   ["f19"] = {key = 0x6e},
   ["/20"] = {key = 0x6f},
   ["f20"] = {key = 0x6f},
   ["/21"] = {key = 0x70},
   ["f21"] = {key = 0x70},
   ["/22"] = {key = 0x71},
   ["f22"] = {key = 0x71},
   ["/23"] = {key = 0x72},
   ["f23"] = {key = 0x72},
   ["/24"] = {key = 0x73},
   ["f24"] = {key = 0x73},

   ["/~"] = {key = "tilde", modifier = "lshift"},
   ["_"] = {key = "minus", modifier = "lshift"},
   ["+"] = {key = "equal", modifier = "lshift"},
   ["{"] = {key = "lbracket", modifier = "lshift"},
   ["}"] = {key = "rbracket", modifier = "lshift"},
   ["|"] = {key = "backslash", modifier = "lshift"},
   [":"] = {key = "semicolon", modifier = "lshift"},
   ["\""] = {key = "quote", modifier = "lshift"},
   ["<"] = {key = "comma", modifier = "lshift"},
   [">"] = {key = "period", modifier = "lshift"},
   ["?"] = {key = "slash", modifier = "lshift"},

   ["`"] = {key = "tilde"},
   ["-"] = {key = "minus"},
   ["="] = {key = "equal"},
   ["["] = {key = "lbracket"},
   ["]"] = {key = "rbracket"},
   ["\\"] = {key = "backslash"},
   [";"] = {key = "semicolon"},
   ["'"] = {key = "quote"},
   [","] = {key = "comma"},
   ["."] = {key = "period"},
   ["//"] = {key = "slash"},
   [" "] = {key = "spacebar"},

   ["!"] = {key = "1", modifier = "lshift"},
   ["@"] = {key = "2", modifier = "lshift"},
   ["/#"] = {key = "3", modifier = "lshift"},
   ["$"] = {key = "4", modifier = "lshift"},
   ["%"] = {key = "5", modifier = "lshift"},
   ["^"] = {key = "6", modifier = "lshift"},
   ["&"] = {key = "7", modifier = "lshift"},
   ["/*"] = {key = "8", modifier = "lshift"},
   ["("] = {key = "9", modifier = "lshift"},
   [")"] = {key = "0", modifier = "lshift"},

   ["1"] = {key = "1"},
   ["2"] = {key = "2"},
   ["3"] = {key = "3"},
   ["4"] = {key = "4"},
   ["5"] = {key = "5"},
   ["6"] = {key = "6"},
   ["7"] = {key = "7"},
   ["8"] = {key = "8"},
   ["9"] = {key = "9"},
   ["0"] = {key = "0"},

   ["A"] = {key = "a", modifier = "lshift"},
   ["B"] = {key = "b", modifier = "lshift"},
   ["C"] = {key = "c", modifier = "lshift"},
   ["D"] = {key = "d", modifier = "lshift"},
   ["E"] = {key = "e", modifier = "lshift"},
   ["F"] = {key = "f", modifier = "lshift"},
   ["G"] = {key = "g", modifier = "lshift"},
   ["H"] = {key = "h", modifier = "lshift"},
   ["I"] = {key = "i", modifier = "lshift"},
   ["J"] = {key = "j", modifier = "lshift"},
   ["K"] = {key = "k", modifier = "lshift"},
   ["L"] = {key = "l", modifier = "lshift"},
   ["M"] = {key = "m", modifier = "lshift"},
   ["N"] = {key = "n", modifier = "lshift"},
   ["O"] = {key = "o", modifier = "lshift"},
   ["P"] = {key = "p", modifier = "lshift"},
   ["Q"] = {key = "q", modifier = "lshift"},
   ["R"] = {key = "r", modifier = "lshift"},
   ["S"] = {key = "s", modifier = "lshift"},
   ["T"] = {key = "t", modifier = "lshift"},
   ["U"] = {key = "u", modifier = "lshift"},
   ["V"] = {key = "v", modifier = "lshift"},
   ["W"] = {key = "w", modifier = "lshift"},
   ["X"] = {key = "x", modifier = "lshift"},
   ["Y"] = {key = "y", modifier = "lshift"},
   ["Z"] = {key = "z", modifier = "lshift"},

   ["a"] = {key = "a"},
   ["b"] = {key = "b"},
   ["c"] = {key = "c"},
   ["d"] = {key = "d"},
   ["e"] = {key = "e"},
   ["f"] = {key = "f"},
   ["g"] = {key = "g"},
   ["h"] = {key = "h"},
   ["i"] = {key = "i"},
   ["j"] = {key = "j"},
   ["k"] = {key = "k"},
   ["l"] = {key = "l"},
   ["m"] = {key = "m"},
   ["n"] = {key = "n"},
   ["o"] = {key = "o"},
   ["p"] = {key = "p"},
   ["q"] = {key = "q"},
   ["r"] = {key = "r"},
   ["s"] = {key = "s"},
   ["t"] = {key = "t"},
   ["u"] = {key = "u"},
   ["v"] = {key = "v"},
   ["w"] = {key = "w"},
   ["x"] = {key = "x"},
   ["y"] = {key = "y"},
   ["z"] = {key = "z"},

   [""] = {key = ""} -- noop
}