--------------------------------------------------------------------------------------------------------------------------------------------
-- Keyboard layout for ll.TypeString(str, delay), ll.PressKey, ll.ReleaseKey, and ll.PressAndReleaseKey
--
--	To create your own keyboard layout, simply save this file to the name of your keyboard layout and update it to fit your keyboard.
--	Update the \llProject\UserConfig.lua file so ll.keyboard equals the new file name.
--	The index is the key you want to recognize, the key is the primary key to press, and the modifier is any modifier needed to be down before you press the key.
--	if you want custom characters, use a forward slash followed by a letter not used. e.i.  "/c" types lctrl
--	currently a single slash is useable with a "//"
--------------------------------------------------------------------------------------------------------------------------------------------
return {

    ["/1"] = { mb = 1 },
    ["/2"] = { mb = 3 },
    ["/3"] = { mb = 2 },
    ["/4"] = { mb = 4 },
    ["/5"] = { mb = 5 },

    ["\n"] = { key = "enter" },
    ["\r"] = { key = "enter" },
    ["\t"] = { key = "tab" },

    ["/a"] = { key = "lalt" },
    ["/A"] = { key = "ralt" },
    ["/c"] = { key = "lctrl" },
    ["/C"] = { key = "rctrl" },
    ["/s"] = { key = "lshift" },
    ["/S"] = { key = "rshift" },
    ["/w"] = { key = "lgui" },
    ["/W"] = { key = "rgui" },

    ["/l"] = { key = "left" },
    ["/u"] = { key = "up" },
    ["/d"] = { key = "down" },
    ["/r"] = { key = "right" },

    ["/e"] = { key = "escape" },
    ["/b"] = { key = "backspace" },
    ["/p"] = { key = "printscreen" },
    ["/i"] = { key = "insert" },
    ["/h"] = { key = "home" },
    ["/m"] = { key = "appkey" },
    ["/U"] = { key = "pageup" },
    ["/D"] = { key = "pagedown" },
    ["/P"] = { key = "pause" },
    ["/E"] = { key = "end" },

    ["/N"] = { key = "numlock" },
    ["/L"] = { key = "capslock" },

    ["/01"] = { key = "f1" },
    ["/02"] = { key = "f2" },
    ["/03"] = { key = "f3" },
    ["/04"] = { key = "f4" },
    ["/05"] = { key = "f5" },
    ["/06"] = { key = "f6" },
    ["/07"] = { key = "f7" },
    ["/08"] = { key = "f8" },
    ["/09"] = { key = "f9" },
    ["/10"] = { key = "f10" },
    ["/11"] = { key = "f11" },
    ["/12"] = { key = "f12" },
    ["/13"] = { key = "f13" },
    ["/14"] = { key = "f14" },
    ["/15"] = { key = "f15" },
    ["/16"] = { key = "f16" },
    ["/17"] = { key = "f17" },
    ["/18"] = { key = "f18" },
    ["/19"] = { key = "f19" },
    ["/20"] = { key = "f20" },
    ["/21"] = { key = "f21" },
    ["/22"] = { key = "f22" },
    ["/23"] = { key = "f23" },
    ["/24"] = { key = "f24" },

    ["�"] = { key = "tilde",        modifier = "lshift" },
    ["_"] = { key = "minus",        modifier = "lshift" },
    ["+"] = { key = "equal",        modifier = "lshift" },
    ["{"] = { key = "lbracket",    modifier = "lshift" },
    ["}"] = { key = "rbracket",    modifier = "lshift" },
    [":"] = { key = "semicolon",    modifier = "lshift" },
    ['@'] = { key = "quote",        modifier = "lshift" },
    ["<"] = { key = "comma",        modifier = "lshift" },
    [">"] = { key = "period",        modifier = "lshift" },
    ["?"] = { key = "slash",        modifier = "lshift" },
    ["|"] = { key = 86,        modifier = "lshift" },
    ["~"] = { key = 43,        modifier = "lshift" },

    ["`"] = { key = "tilde" },
    ["-"] = { key = "minus" },
    ["="] = { key = "equal" },
    ["["] = { key = "lbracket" },
    ["]"] = { key = "rbracket" },
    [";"] = { key = "semicolon" },
    ["'"] = { key = "quote" },
    [","] = { key = "comma" },
    ["."] = { key = "period" },
    ["//"] = { key = "slash" },
    ["\\"] = { key = 86 },
    ["#"] = { key = 43 },
    [" "] = { key = "spacebar" },

    ["!"] = { key = "1", modifier = "lshift" },
    ['"'] = { key = "2", modifier = "lshift" },
    ["�"] = { key = "3", modifier = "lshift" },
    ["$"] = { key = "4", modifier = "lshift" },
    ["%"] = { key = "5", modifier = "lshift" },
    ["^"] = { key = "6", modifier = "lshift" },
    ["&"] = { key = "7", modifier = "lshift" },
    ["*"] = { key = "8", modifier = "lshift" },
    ["("] = { key = "9", modifier = "lshift" },
    [")"] = { key = "0", modifier = "lshift" },


    ["1"] = { key = "1" },
    ["2"] = { key = "2" },
    ["3"] = { key = "3" },
    ["4"] = { key = "4" },
    ["5"] = { key = "5" },
    ["6"] = { key = "6" },
    ["7"] = { key = "7" },
    ["8"] = { key = "8" },
    ["9"] = { key = "9" },
    ["0"] = { key = "0" },


    ["A"] = { key = "a", modifier = "lshift" },
    ["B"] = { key = "b", modifier = "lshift" },
    ["C"] = { key = "c", modifier = "lshift" },
    ["D"] = { key = "d", modifier = "lshift" },
    ["E"] = { key = "e", modifier = "lshift" },
    ["F"] = { key = "f", modifier = "lshift" },
    ["G"] = { key = "g", modifier = "lshift" },
    ["H"] = { key = "h", modifier = "lshift" },
    ["I"] = { key = "i", modifier = "lshift" },
    ["J"] = { key = "j", modifier = "lshift" },
    ["K"] = { key = "k", modifier = "lshift" },
    ["L"] = { key = "l", modifier = "lshift" },
    ["M"] = { key = "m", modifier = "lshift" },
    ["N"] = { key = "n", modifier = "lshift" },
    ["O"] = { key = "o", modifier = "lshift" },
    ["P"] = { key = "p", modifier = "lshift" },
    ["Q"] = { key = "q", modifier = "lshift" },
    ["R"] = { key = "r", modifier = "lshift" },
    ["S"] = { key = "s", modifier = "lshift" },
    ["T"] = { key = "t", modifier = "lshift" },
    ["U"] = { key = "u", modifier = "lshift" },
    ["V"] = { key = "v", modifier = "lshift" },
    ["W"] = { key = "w", modifier = "lshift" },
    ["X"] = { key = "x", modifier = "lshift" },
    ["Y"] = { key = "y", modifier = "lshift" },
    ["Z"] = { key = "z", modifier = "lshift" },

    ["a"] = { key = "a" },
    ["b"] = { key = "b" },
    ["c"] = { key = "c" },
    ["d"] = { key = "d" },
    ["e"] = { key = "e" },
    ["f"] = { key = "f" },
    ["g"] = { key = "g" },
    ["h"] = { key = "h" },
    ["i"] = { key = "i" },
    ["j"] = { key = "j" },
    ["k"] = { key = "k" },
    ["l"] = { key = "l" },
    ["m"] = { key = "m" },
    ["n"] = { key = "n" },
    ["o"] = { key = "o" },
    ["p"] = { key = "p" },
    ["q"] = { key = "q" },
    ["r"] = { key = "r" },
    ["s"] = { key = "s" },
    ["t"] = { key = "t" },
    ["u"] = { key = "u" },
    ["v"] = { key = "v" },
    ["w"] = { key = "w" },
    ["x"] = { key = "x" },
    ["y"] = { key = "y" },
    ["z"] = { key = "z" },
}