--------------------------------------------------------------------------------------------------------------------------------------------
--	The index is the key you want to recognize, the key is the primary key to press, and the modifier is any modifier needed to be down before you press the key.
--	if you want custom characters, use a forward slash followed by a letter not used. e.i.  "/c" types lctrl
--	currently a single slash is useable with a "//"
--------------------------------------------------------------------------------------------------------------------------------------------
return { --- American Key Layout
   ["/1"] = {mb = 1},
   ["/2"] = {mb = 3},
   ["/3"] = {mb = 2},
   ["/4"] = {mb = 4},
   ["/5"] = {mb = 5},
   ["/6"] = {mb = 6},
   ["/7"] = {mb = 7},

   ["\n"] = {key = 0x28},
   ["\r"] = {key = 0x28},
   ["enter"] = {key = 0x28},
   ["\t"] = {key = 0x2b},
   ["tab"] = {key = 0x2b},

   ["/a"] = {key = 0xe2},
   ["lalt"] = {key = 0xe2},
   ["/A"] = {key = 0xe6},
   ["ralt"] = {key = 0xe6},
   ["/c"] = {key = 0xe0},
   ["lctrl"] = {key = 0xe0},
   ["/C"] = {key = 0xe1},
   ["rctrl"] = {key = 0xe1},
   ["/s"] = {key = 0xe1},
   ["lshift"] = {key = 0xe1},
   ["/S"] = {key = 0xe5},
   ["rshift"] = {key = 0xe5},
   ["/w"] = {key = 0xe3},
   ["lgui"] = {key = 0xe3},
   ["/W"] = {key = 0xe7},
   ["rgui"] = {key = 0xe7},

   ["/l"] = {key = 0x50},
   ["left"] = {key = 0x50},
   ["/u"] = {key = 0x51},
   ["up"] = {key = 0x51},
   ["/d"] = {key = 0x52},
   ["down"] = {key = 0x52},
   ["/r"] = {key = 0x4f},
   ["right"] = {key = 0x4f},

   ["/e"] = {key = 0x29},
   ["escape"] = {key = 0x29},
   ["/b"] = {key = 0x2a},
   ["backspace"] = {key = 0x2a},
   ["/p"] = {key = 0x46},
   ["printscreen"] = {key = 0x46},
   ["/i"] = {key = 0x49},
   ["insert"] = {key = 0x49},
   ["/h"] = {key = 0x4a},
   ["home"] = {key = 0x4a},
   ["/m"] = {key = 0x65},
   ["appkey"] = {key = 0x65},
   ["/U"] = {key = 0x4b},
   ["pageup"] = {key = 0x4b},
   ["/D"] = {key = 0x4e},
   ["pagedown"] = {key = 0x4e},
   ["/P"] = {key = 0x48},
   ["pause"] = {key = 0x48},
   ["/E"] = {key = 0x4d},
   ["end"] = {key = 0x4d},

   ["numslash"] = {key = 0x54},
   ["num1"] = {key = 0x59},
   ["num2"] = {key = 0x5a},
   ["num3"] = {key = 0x5b},
   ["num4"] = {key = 0x5c},
   ["num5"] = {key = 0x5d},
   ["num6"] = {key = 0x5e},
   ["num7"] = {key = 0x5f},
   ["num8"] = {key = 0x60},
   ["num9"] = {key = 0x61},
   ["num0"] = {key = 0x62},

   ["/-"] = {key = 0x56},
   ["numminus"] = {key = 0x56},
   ["/+"] = {key = 0x57},
   ["numplus"] = {key = 0x57},
   ["/n"] = {key = 0x58},
   ["numenter"] = {key = 0x58},
   ["/."] = {key = 0x63},
   ["numperiod"] = {key = 0x63},

   ["/N"] = {key = 0x53},
   ["numlock"] = {key = 0x53},
   ["/L"] = {key = 0x39},
   ["capslock"] = {key = 0x39},

   ["/01"] = {key = 0x3a},
   ["f1"] = {key = 0x3a},
   ["/02"] = {key = 0x3b},
   ["f2"] = {key = 0x3b},
   ["/03"] = {key = 0x3c},
   ["f3"] = {key = 0x3c},
   ["/04"] = {key = 0x3d},
   ["f4"] = {key = 0x3d},
   ["/05"] = {key = 0x3e},
   ["f5"] = {key = 0x3e},
   ["/06"] = {key = 0x3f},
   ["f6"] = {key = 0x3f},
   ["/07"] = {key = 0x40},
   ["f7"] = {key = 0x40},
   ["/08"] = {key = 0x41},
   ["f8"] = {key = 0x41},
   ["/09"] = {key = 0x42},
   ["f9"] = {key = 0x42},
   ["/10"] = {key = 0x43},
   ["f10"] = {key = 0x43},
   ["/11"] = {key = 0x44},
   ["f11"] = {key = 0x44},
   ["/12"] = {key = 0x45},
   ["f12"] = {key = 0x45},
   ["/13"] = {key = 0x68},
   ["f13"] = {key = 0x68},
   ["/14"] = {key = 0x69},
   ["f14"] = {key = 0x69},
   ["/15"] = {key = 0x6a},
   ["f15"] = {key = 0x6a},
   ["/16"] = {key = 0x6b},
   ["f16"] = {key = 0x6b},
   ["/17"] = {key = 0x6c},
   ["f17"] = {key = 0x6c},
   ["/18"] = {key = 0x6d},
   ["f18"] = {key = 0x6d},
   ["/19"] = {key = 0x6e},
   ["f19"] = {key = 0x6e},
   ["/20"] = {key = 0x6f},
   ["f20"] = {key = 0x6f},
   ["/21"] = {key = 0x70},
   ["f21"] = {key = 0x70},
   ["/22"] = {key = 0x71},
   ["f22"] = {key = 0x71},
   ["/23"] = {key = 0x72},
   ["f23"] = {key = 0x72},
   ["/24"] = {key = 0x73},
   ["f24"] = {key = 0x73},

   ["/~"] = {key = 0x32, modifier = "lshift"},
   ["_"] = {key = 0x2d, modifier = "lshift"},
   ["+"] = {key = 0x2e, modifier = "lshift"},
   ["{"] = {key = 0x2f, modifier = "lshift"},
   ["}"] = {key = 0x30, modifier = "lshift"},
   ["|"] = {key = 0x31, modifier = "lshift"},
   [":"] = {key = 0x33, modifier = "lshift"},
   ["\""] = {key = 0x34, modifier = "lshift"},
   ["<"] = {key = 0x36, modifier = "lshift"},
   [">"] = {key = 0x37, modifier = "lshift"},
   ["?"] = {key = 0x38, modifier = "lshift"},

   ["`"] = {key = 0x32},
   ["-"] = {key = 0x2d},
   ["="] = {key = 0x2e},
   ["["] = {key = 0x2f},
   ["]"] = {key = 0x30},
   ["\\"] = {key = 0x31},
   [";"] = {key = 0x33},
   ["'"] = {key = 0x34},
   [","] = {key = 0x36},
   ["."] = {key = 0x37},
   ["//"] = {key = 0x38},
   [" "] = {key = 0x2c},

   ["!"] = {key = 0x1e, modifier = "lshift"},
   ["@"] = {key = 0x1f, modifier = "lshift"},
   ["/#"] = {key = 0x20, modifier = "lshift"},
   ["$"] = {key = 0x21, modifier = "lshift"},
   ["%"] = {key = 0x22, modifier = "lshift"},
   ["^"] = {key = 0x23, modifier = "lshift"},
   ["&"] = {key = 0x24, modifier = "lshift"},
   ["/*"] = {key = 0x25, modifier = "lshift"},
   ["("] = {key = 0x26, modifier = "lshift"},
   [")"] = {key = 0x27, modifier = "lshift"},

   ["1"] = {key = 0x1e},
   ["2"] = {key = 0x1f},
   ["3"] = {key = 0x20},
   ["4"] = {key = 0x21},
   ["5"] = {key = 0x22},
   ["6"] = {key = 0x23},
   ["7"] = {key = 0x24},
   ["8"] = {key = 0x25},
   ["9"] = {key = 0x26},
   ["0"] = {key = 0x27},

   ["A"] = {key = 0x04, modifier = "lshift"},
   ["B"] = {key = 0x05, modifier = "lshift"},
   ["C"] = {key = 0x06, modifier = "lshift"},
   ["D"] = {key = 0x07, modifier = "lshift"},
   ["E"] = {key = 0x08, modifier = "lshift"},
   ["F"] = {key = 0x09, modifier = "lshift"},
   ["G"] = {key = 0x0a, modifier = "lshift"},
   ["H"] = {key = 0x0b, modifier = "lshift"},
   ["I"] = {key = 0x0c, modifier = "lshift"},
   ["J"] = {key = 0x0d, modifier = "lshift"},
   ["K"] = {key = 0x0e, modifier = "lshift"},
   ["L"] = {key = 0x0f, modifier = "lshift"},
   ["M"] = {key = 0x10, modifier = "lshift"},
   ["N"] = {key = 0x11, modifier = "lshift"},
   ["O"] = {key = 0x12, modifier = "lshift"},
   ["P"] = {key = 0x13, modifier = "lshift"},
   ["Q"] = {key = 0x14, modifier = "lshift"},
   ["R"] = {key = 0x15, modifier = "lshift"},
   ["S"] = {key = 0x16, modifier = "lshift"},
   ["T"] = {key = 0x17, modifier = "lshift"},
   ["U"] = {key = 0x18, modifier = "lshift"},
   ["V"] = {key = 0x19, modifier = "lshift"},
   ["W"] = {key = 0x1a, modifier = "lshift"},
   ["X"] = {key = 0x1b, modifier = "lshift"},
   ["Z"] = {key = 0x1c, modifier = "lshift"},
   ["Y"] = {key = 0x1d, modifier = "lshift"},

   ["a"] = {key = 0x04},
   ["b"] = {key = 0x05},
   ["c"] = {key = 0x06},
   ["d"] = {key = 0x07},
   ["e"] = {key = 0x08},
   ["f"] = {key = 0x09},
   ["g"] = {key = 0x0a},
   ["h"] = {key = 0x0b},
   ["i"] = {key = 0x0c},
   ["j"] = {key = 0x0d},
   ["k"] = {key = 0x0e},
   ["l"] = {key = 0x0f},
   ["m"] = {key = 0x10},
   ["n"] = {key = 0x11},
   ["o"] = {key = 0x12},
   ["p"] = {key = 0x13},
   ["q"] = {key = 0x14},
   ["r"] = {key = 0x15},
   ["s"] = {key = 0x16},
   ["t"] = {key = 0x17},
   ["u"] = {key = 0x18},
   ["v"] = {key = 0x19},
   ["w"] = {key = 0x1a},
   ["x"] = {key = 0x1b},
   ["z"] = {key = 0x1c},
   ["y"] = {key = 0x1d},

   [""] = {key = ""} -- noop
}