    --------------------------------------------------------------------------------------------------------------------------------------------
    --   The index is the key you want to recognize, the key is the primary key to press, and the modifier is any modifier needed to be down before you press the key.
    --   if you want custom characters, use a forward slash followed by a letter not used. e.i.  "/c" types lctrl
    --   currently a single slash is useable with a "//"
    --------------------------------------------------------------------------------------------------------------------------------------------
-- DE_Deutsch.lua
local tl = ...
tl._KEYBOARD = {
    ["/1"]  = { mb = 1 },
	["/2"]  = { mb = 3 },
	["/3"]  = { mb = 2 },
	["/4"]  = { mb = 4 },
	["/5"]  = { mb = 5 },

	["\n"]  = { key = "enter" },
	["\r"]  = { key = "enter" },
	["\t"]  = { key = "tab" },
	["/e"]  = { key = "escape" },
	["/r"]  = { key = "right" },
	["/l"]  = { key = "left" },
	["/u"]  = { key = "up" },
	["/d"]  = { key = "down" },

	["/01"]  = { key = "f1" },
	["/02"]  = { key = "f2" },
	["/03"]  = { key = "f3" },
	["/04"]  = { key = "f4" },
	["/05"]  = { key = "f5" },
	["/06"]  = { key = "f6" },
	["/07"]  = { key = "f7" },
	["/08"]  = { key = "f8" },
	["/09"]  = { key = "f9" },
	["/10"]  = { key = "f10" },
	["/11"]  = { key = "f11" },
	["/12"]  = { key = "f12" },
	["/13"]  = { key = "f13" },
	["/14"]  = { key = "f14" },
	["/15"]  = { key = "f15" },
	["/16"]  = { key = "f16" },
	["/17"]  = { key = "f17" },
	["/18"]  = { key = "f18" },
	["/19"]  = { key = "f19" },
	["/20"]  = { key = "f20" },
	["/21"]  = { key = "f21" },
	["/22"]  = { key = "f22" },
	["/23"]  = { key = "f23" },
	["/24"]  = { key = "f24" },

	["/a"]  = { key = "lalt" },
	["/A"]  = { key = "ralt" },
	["/c"]  = { key = "lctrl" },
	["/C"]  = { key = "rctrl" },
	["/s"]  = { key = "lshift" },
	["/S"]  = { key = "rshift" },
	["/w"]  = { key = 0x5b },
	["/W"]  = { key = 0x5c },
	["/b"]  = { key = "backspace" },
	["/p"]  = { key = "printscreen" },

	["/~"]   = { key = "tilde",      modifier = "lshift" },
	["?"]   = { key = "minus",      modifier = "lshift" },
	["`"]   = { { key = "equal",    modifier = "lshift" },          { key = "spacebar" } },
	["Ü"]   = { key = "lbracket",   modifier = "lshift" },
	["/*"]   = { key = "rbracket",   modifier = "lshift" },
	["Ö"]   = { key = "semicolon",  modifier = "lshift" },
	['Ä']   = { key = "quote",      modifier = "lshift" },
	[";"]   = { key = "comma",      modifier = "lshift" },
	[":"]   = { key = "period",     modifier = "lshift" },
	["_"]   = { key = 0x35,         modifier = "lshift" },
	[">"]   = { key = 0x56,         modifier = "lshift" },
	["'"]   = { key = 0x2b,         modifier = "lshift" },

	["/#"]   = { { key = "tilde" },                                  { key = "spacebar" } },
	["ß"]   = { key = "minus" },
	["´"]   = { { key = "equal" },                                  { key = "spacebar" } },
	["ü"]   = { key = "lbracket" },
	["+"]   = { key = "rbracket" },
	["ö"]   = { key = "semicolon" },
	["ä"]   = { key = "quote" },
	[","]   = { key = "comma" },
	["."]   = { key = "period" },
	["-"]   = { key = 0x35 },
	["<"]   = { key = 0x56 },
	["/#"]   = { key = 0x2b },
	[" "]   = { key = "spacebar" },

	["²"]   = { key = "2",          modifier = {"lalt","lctrl"} },
	["³"]   = { key = "3",          modifier = {"lalt","lctrl"} },
	["{"]   = { key = "7",          modifier = {"lalt","lctrl"} },
	["["]   = { key = "8",          modifier = {"lalt","lctrl"} },
	["]"]   = { key = "9",          modifier = {"lalt","lctrl"} },
	["}"]   = { key = "0",          modifier = {"lalt","lctrl"} },
	["\\"]  = { key = "minus",      modifier = {"lalt","lctrl"} },
	["@"]   = { key = "q",          modifier = {"lalt","lctrl"} },
	["€"]   = { key = "e",          modifier = {"lalt","lctrl"} },
	["/~"]   = { key = "rbracket",   modifier = {"lalt","lctrl"} },
	["|"]   = { key = 0x56,         modifier = {"lalt","lctrl"} },
	["µ"]   = { key = "m",          modifier = {"lalt","lctrl"} },

	["!"]   = { key = "1", 			modifier = "lshift" },
	['"']   = { key = "2", 			modifier = "lshift" },
	["§"]   = { key = "3", 			modifier = "lshift" },
	["$"]   = { key = "4", 			modifier = "lshift" },
	["%"]   = { key = "5", 			modifier = "lshift" },
	["&"]   = { key = "6", 			modifier = "lshift" },
	["//"]  = { key = "7", 			modifier = "lshift" },
	["("]   = { key = "8", 			modifier = "lshift" },
	[")"]   = { key = "9", 			modifier = "lshift" },
	["="]   = { key = "0", 			modifier = "lshift" },

	["1"]   = { key = "1" },
	["2"]   = { key = "2" },
	["3"]   = { key = "3" },
	["4"]   = { key = "4" },
	["5"]   = { key = "5" },
	["6"]   = { key = "6" },
	["7"]   = { key = "7" },
	["8"]   = { key = "8" },
	["9"]   = { key = "9" },
	["0"]   = { key = "0" },

	["A"]   = { key = "a", modifier = "lshift" },
	["B"]   = { key = "b", modifier = "lshift" },
	["C"]   = { key = "c", modifier = "lshift" },
	["D"]   = { key = "d", modifier = "lshift" },
	["E"]   = { key = "e", modifier = "lshift" },
	["F"]   = { key = "f", modifier = "lshift" },
	["G"]   = { key = "g", modifier = "lshift" },
	["H"]   = { key = "h", modifier = "lshift" },
	["I"]   = { key = "i", modifier = "lshift" },
	["J"]   = { key = "j", modifier = "lshift" },
	["K"]   = { key = "k", modifier = "lshift" },
	["L"]   = { key = "l", modifier = "lshift" },
	["M"]   = { key = "m", modifier = "lshift" },
	["N"]   = { key = "n", modifier = "lshift" },
	["O"]   = { key = "o", modifier = "lshift" },
	["P"]   = { key = "p", modifier = "lshift" },
	["Q"]   = { key = "q", modifier = "lshift" },
	["R"]   = { key = "r", modifier = "lshift" },
	["S"]   = { key = "s", modifier = "lshift" },
	["T"]   = { key = "t", modifier = "lshift" },
	["U"]   = { key = "u", modifier = "lshift" },
	["V"]   = { key = "v", modifier = "lshift" },
	["W"]   = { key = "w", modifier = "lshift" },
	["X"]   = { key = "x", modifier = "lshift" },
	["Z"]   = { key = "y", modifier = "lshift" },
	["Y"]   = { key = "z", modifier = "lshift" },

	["a"]   = { key = "a" },
	["b"]   = { key = "b" },
	["c"]   = { key = "c" },
	["d"]   = { key = "d" },
	["e"]   = { key = "e" },
	["f"]   = { key = "f" },
	["g"]   = { key = "g" },
	["h"]   = { key = "h" },
	["i"]   = { key = "i" },
	["j"]   = { key = "j" },
	["k"]   = { key = "k" },
	["l"]   = { key = "l" },
	["m"]   = { key = "m" },
	["n"]   = { key = "n" },
	["o"]   = { key = "o" },
	["p"]   = { key = "p" },
	["q"]   = { key = "q" },
	["r"]   = { key = "r" },
	["s"]   = { key = "s" },
	["t"]   = { key = "t" },
	["u"]   = { key = "u" },
	["v"]   = { key = "v" },
	["w"]   = { key = "w" },
	["x"]   = { key = "x" },
	["z"]   = { key = "y" },
	["y"]   = { key = "z" },

	["Á"]   = { { key = "equal" }                           , { key = "a" } },
	["À"]   = { { key = "equal", modifier = "lshift" }      , { key = "a", modifier = "lshift" } },
	["Â"]   = { { key = "tilde" }                           , { key = "a" } },
	["É"]   = { { key = "equal" }                           , { key = "e" } },
	["È"]   = { { key = "equal", modifier = "lshift" }      , { key = "e", modifier = "lshift" } },
	["Ê"]   = { { key = "tilde" }                           , { key = "e" } },
	["Í"]   = { { key = "equal" }                           , { key = "i" } },
	["Ì"]   = { { key = "equal", modifier = "lshift" }      , { key = "i", modifier = "lshift" } },
	["Î"]   = { { key = "tilde" }                           , { key = "i" } },
	["Ó"]   = { { key = "equal" }                           , { key = "o" } },
	["Ò"]   = { { key = "equal", modifier = "lshift" }      , { key = "o", modifier = "lshift" } },
	["Ô"]   = { { key = "tilde" }                           , { key = "o" } },
	["Ú"]   = { { key = "equal" }                           , { key = "u" } },
	["Ù"]   = { { key = "equal", modifier = "lshift" }      , { key = "u", modifier = "lshift" } },
	["Û"]   = { { key = "tilde" }                           , { key = "u" } },

	["á"]   = { { key = "equal" }                           , { key = "a" } },
	["à"]   = { { key = "equal", modifier = "lshift" }      , { key = "a" } },
	["â"]   = { { key = "tilde" }                           , { key = "a" } },
	["é"]   = { { key = "equal" }                           , { key = "e" } },
	["è"]   = { { key = "equal", modifier = "lshift" }      , { key = "e" } },
	["ê"]   = { { key = "tilde" }                           , { key = "e" } },
	["í"]   = { { key = "equal" }                           , { key = "i" } },
	["ì"]   = { { key = "equal", modifier = "lshift" }      , { key = "i" } },
	["î"]   = { { key = "tilde" }                           , { key = "i" } },
	["ó"]   = { { key = "equal" }                           , { key = "o" } },
	["ò"]   = { { key = "equal", modifier = "lshift" }      , { key = "o" } },
	["ô"]   = { { key = "tilde" }                           , { key = "o" } },
	["ú"]   = { { key = "equal" }                           , { key = "u" } },
	["ù"]   = { { key = "equal", modifier = "lshift" }      , { key = "u" } },
	["û"]   = { { key = "tilde" }                           , { key = "u" } },
}

tl.logiKeys={["escape"]=1,["f1"]=1,["f2"]=1,["f3"]=1,["f4"]=1,["f5"]=1,["f6"]=1,["f7"]=1,["f8"]=1,["f9"]=1,["f10"]=1,["f11"]=1,["f12"]=1,["f13"]=1,["f14"]=1,["f15"]=1,["f16"]=1,["f17"]=1,["f18"]=1,["f19"]=1,["f20"]=1,["f21"]=1,["f22"]=1,["f23"]=1,["f24"]=1,["printscreen"]=1,["scrolllock"]=1,["pause"]=1,["tilde"]=1,["1"]=1,[1]=1,["2"]=1,[2]=1,["3"]=1,[3]=1,["4"]=1,[4]=1,["5"]=1,[5]=1,["6"]=1,[6]=1,["7"]=1,[7]=1,["8"]=1,[8]=1,["9"]=1,[9]=1,["0"]=1,[0]=1,["minus"]=1,["equal"]=1,["backspace"]=1,["tab"]=1,["q"]=1,["w"]=1,["e"]=1,["r"]=1,["t"]=1,["y"]=1,["u"]=1,["I"]=1,["o"]=1,["p"]=1,["lbracket"]=1,["rbracket"]=1,["backslash"]=1,["capslock"]=1,["a"]=1,["s"]=1,["d"]=1,["f"]=1,["g"]=1,["h"]=1,["j"]=1,["k"]=1,["l"]=1,["semicolon"]=1,["quote"]=1,["enter"]=1,["lshift"]=1,["non_us_slash"]=1,["z"]=1,["x"]=1,["c"]=1,["v"]=1,["b"]=1,["n"]=1,["m"]=1,["comma"]=1,["period"]=1,["slash"]=1,["rshift"]=1,["lctrl"]=1,["lgui"]=1,["lalt"]=1,["spacebar"]=1,["ralt"]=1,["rgui"]=1,["appkey"]=1,["rctrl"]=1,["insert"]=1,["home"]=1,["pageup"]=1,["delete"]=1,["end"]=1,["pagedown"]=1,["up"]=1,["left"]=1,["down"]=1,["right"]=1,["numlock"]=1,["numslash"]=1,["numminus"]=1,["num7"]=1,["num8"]=1,["num9"]=1,["numplus"]=1,["num4"]=1,["num5"]=1,["num6"]=1,["num1"]=1,["num2"]=1,["num3"]=1,["numenter"]=1,["num0"]=1,["numperiod"]=1}
-- eof
