--------------------------------------------------------------------------------------------------------------------------------------------
--   The index is the key you want to recognize, the key is the primary key to press, and the modifier is any modifier needed to be down before you press the key.
--   if you want custom characters, use a forward slash followed by a letter not used. e.i.  "/c" types lctrl
--   currently a single slash is useable with a "//"
--------------------------------------------------------------------------------------------------------------------------------------------
-- DE_Deutsch.lua
---@type MainLibObject
local tl = ...
tl.keys.keyboardDefinition = {
    ["/1"] = { mb = 1 },
    ["/2"] = { mb = 3 },
    ["/3"] = { mb = 2 },
    ["/4"] = { mb = 4 },
    ["/5"] = { mb = 5 },

    ["\n"] = { key = "enter" },
    ["\r"] = { key = "enter" },
    ["\t"] = { key = "tab" },

    ["/a"] = { key = "lalt" },
    ["/A"] = { key = "ralt" },
    ["/c"] = { key = "lctrl" },
    ["/C"] = { key = "rctrl" },
    ["/s"] = { key = "lshift" },
    ["/S"] = { key = "rshift" },
    ["/w"] = { key = "lgui" },
    ["/W"] = { key = "rgui" },

    ["/l"] = { key = "left" },
    ["/u"] = { key = "up" },
    ["/d"] = { key = "down" },
    ["/r"] = { key = "right" },

    ["/e"] = { key = "escape" },
    ["/b"] = { key = "backspace" },
    ["/p"] = { key = "printscreen" },
    ["/i"] = { key = "insert" },
    ["/h"] = { key = "home" },
    ["/m"] = { key = "appkey" },
    ["/U"] = { key = "pageup" },
    ["/D"] = { key = "pagedown" },
    ["/P"] = { key = "pause" },
    ["/E"] = { key = "end" },

    ["/N"] = { key = "numlock" },
    ["/L"] = { key = "capslock" },

    ["/01"] = { key = "f1" },
    ["/02"] = { key = "f2" },
    ["/03"] = { key = "f3" },
    ["/04"] = { key = "f4" },
    ["/05"] = { key = "f5" },
    ["/06"] = { key = "f6" },
    ["/07"] = { key = "f7" },
    ["/08"] = { key = "f8" },
    ["/09"] = { key = "f9" },
    ["/10"] = { key = "f10" },
    ["/11"] = { key = "f11" },
    ["/12"] = { key = "f12" },
    ["/13"] = { key = "f13" },
    ["/14"] = { key = "f14" },
    ["/15"] = { key = "f15" },
    ["/16"] = { key = "f16" },
    ["/17"] = { key = "f17" },
    ["/18"] = { key = "f18" },
    ["/19"] = { key = "f19" },
    ["/20"] = { key = "f20" },
    ["/21"] = { key = "f21" },
    ["/22"] = { key = "f22" },
    ["/23"] = { key = "f23" },
    ["/24"] = { key = "f24" },

    ["°"] = { key = "tilde", modifier = "lshift" },
    ["?"] = { key = "minus", modifier = "lshift" },
    ["`"] = { { key = "equal", modifier = "lshift" }, { key = "spacebar" } },
    ["Ü"] = { key = "lbracket", modifier = "lshift" },
    ["/*"] = { key = "rbracket", modifier = "lshift" },
    ["Ö"] = { key = "semicolon", modifier = "lshift" },
    ["Ä"] = { key = "quote", modifier = "lshift" },
    [";"] = { key = "comma", modifier = "lshift" },
    [":"] = { key = "period", modifier = "lshift" },
    ["_"] = { key = 53, modifier = "lshift" },
    [">"] = { key = 86, modifier = "lshift" },
    ["'"] = { key = 43, modifier = "lshift" },
    ["^"] = { { key = "tilde" }, { key = "spacebar" } },
    ["ß"] = { key = "minus" },
    ["´"] = { { key = "equal" }, { key = "spacebar" } },
    ["ü"] = { key = "lbracket" },
    ["+"] = { key = "rbracket" },
    ["ö"] = { key = "semicolon" },
    ["ä"] = { key = "quote" },
    [","] = { key = "comma" },
    ["."] = { key = "period" },
    ["-"] = { key = 53 },
    ["<"] = { key = 86 },
    ["/#"] = { key = 43 },
    [" "] = { key = "spacebar" },
    ["²"] = { key = "2", modifier = { "lalt", "lctrl" } },
    ["³"] = { key = "3", modifier = { "lalt", "lctrl" } },
    ["{"] = { key = "7", modifier = { "lalt", "lctrl" } },
    ["["] = { key = "8", modifier = { "lalt", "lctrl" } },
    ["]"] = { key = "9", modifier = { "lalt", "lctrl" } },
    ["}"] = { key = "0", modifier = { "lalt", "lctrl" } },
    ["\\"] = { key = "minus", modifier = { "lalt", "lctrl" } },
    ["@"] = { key = "q", modifier = { "lalt", "lctrl" } },
    ["€"] = { key = "e", modifier = { "lalt", "lctrl" } },
    ["/~"] = { key = "rbracket", modifier = { "lalt", "lctrl" } },
    ["/|"] = { key = 86, modifier = { "lalt", "lctrl" } },
    ["µ"] = { key = "m", modifier = { "lalt", "lctrl" } },
    ["!"] = { key = "1", modifier = "lshift" },
    ['"'] = { key = "2", modifier = "lshift" },
    ["§"] = { key = "3", modifier = "lshift" },
    ["$"] = { key = "4", modifier = "lshift" },
    ["%"] = { key = "5", modifier = "lshift" },
    ["&"] = { key = "6", modifier = "lshift" },
    ["//"] = { key = "7", modifier = "lshift" },
    ["("] = { key = "8", modifier = "lshift" },
    [")"] = { key = "9", modifier = "lshift" },
    ["="] = { key = "0", modifier = "lshift" },

    ["1"] = { key = "1" },
    ["2"] = { key = "2" },
    ["3"] = { key = "3" },
    ["4"] = { key = "4" },
    ["5"] = { key = "5" },
    ["6"] = { key = "6" },
    ["7"] = { key = "7" },
    ["8"] = { key = "8" },
    ["9"] = { key = "9" },
    ["0"] = { key = "0" },

    [1] = { key = "1" },
    [2] = { key = "2" },
    [3] = { key = "3" },
    [4] = { key = "4" },
    [5] = { key = "5" },
    [6] = { key = "6" },
    [7] = { key = "7" },
    [8] = { key = "8" },
    [9] = { key = "9" },
    [0] = { key = "0" },

    ["A"] = { key = "a", modifier = "lshift" },
    ["B"] = { key = "b", modifier = "lshift" },
    ["C"] = { key = "c", modifier = "lshift" },
    ["D"] = { key = "d", modifier = "lshift" },
    ["E"] = { key = "e", modifier = "lshift" },
    ["F"] = { key = "f", modifier = "lshift" },
    ["G"] = { key = "g", modifier = "lshift" },
    ["H"] = { key = "h", modifier = "lshift" },
    ["I"] = { key = "i", modifier = "lshift" },
    ["J"] = { key = "j", modifier = "lshift" },
    ["K"] = { key = "k", modifier = "lshift" },
    ["L"] = { key = "l", modifier = "lshift" },
    ["M"] = { key = "m", modifier = "lshift" },
    ["N"] = { key = "n", modifier = "lshift" },
    ["O"] = { key = "o", modifier = "lshift" },
    ["P"] = { key = "p", modifier = "lshift" },
    ["Q"] = { key = "q", modifier = "lshift" },
    ["R"] = { key = "r", modifier = "lshift" },
    ["S"] = { key = "s", modifier = "lshift" },
    ["T"] = { key = "t", modifier = "lshift" },
    ["U"] = { key = "u", modifier = "lshift" },
    ["V"] = { key = "v", modifier = "lshift" },
    ["W"] = { key = "w", modifier = "lshift" },
    ["X"] = { key = "x", modifier = "lshift" },
    ["Z"] = { key = "y", modifier = "lshift" },
    ["Y"] = { key = "z", modifier = "lshift" },

    ["a"] = { key = "a" },
    ["b"] = { key = "b" },
    ["c"] = { key = "c" },
    ["d"] = { key = "d" },
    ["e"] = { key = "e" },
    ["f"] = { key = "f" },
    ["g"] = { key = "g" },
    ["h"] = { key = "h" },
    ["i"] = { key = "i" },
    ["j"] = { key = "j" },
    ["k"] = { key = "k" },
    ["l"] = { key = "l" },
    ["m"] = { key = "m" },
    ["n"] = { key = "n" },
    ["o"] = { key = "o" },
    ["p"] = { key = "p" },
    ["q"] = { key = "q" },
    ["r"] = { key = "r" },
    ["s"] = { key = "s" },
    ["t"] = { key = "t" },
    ["u"] = { key = "u" },
    ["v"] = { key = "v" },
    ["w"] = { key = "w" },
    ["x"] = { key = "x" },
    ["z"] = { key = "y" },
    ["y"] = { key = "z" },

    ["Á"] = { { key = "equal" }, { key = "a" } },
    ["À"] = { { key = "equal", modifier = "lshift" }, { key = "a", modifier = "lshift" } },
    ["Â"] = { { key = "tilde" }, { key = "a" } },
    ["É"] = { { key = "equal" }, { key = "e" } },
    ["È"] = { { key = "equal", modifier = "lshift" }, { key = "e", modifier = "lshift" } },
    ["Ê"] = { { key = "tilde" }, { key = "e" } },
    ["Í"] = { { key = "equal" }, { key = "i" } },
    ["Ì"] = { { key = "equal", modifier = "lshift" }, { key = "i", modifier = "lshift" } },
    ["Î"] = { { key = "tilde" }, { key = "i" } },
    ["Ó"] = { { key = "equal" }, { key = "o" } },
    ["Ò"] = { { key = "equal", modifier = "lshift" }, { key = "o", modifier = "lshift" } },
    ["Ô"] = { { key = "tilde" }, { key = "o" } },
    ["Ú"] = { { key = "equal" }, { key = "u" } },
    ["Ù"] = { { key = "equal", modifier = "lshift" }, { key = "u", modifier = "lshift" } },
    ["Û"] = { { key = "tilde" }, { key = "u" } },

    ["á"] = { { key = "equal" }, { key = "a" } },
    ["à"] = { { key = "equal", modifier = "lshift" }, { key = "a" } },
    ["â"] = { { key = "tilde" }, { key = "a" } },
    ["é"] = { { key = "equal" }, { key = "e" } },
    ["è"] = { { key = "equal", modifier = "lshift" }, { key = "e" } },
    ["ê"] = { { key = "tilde" }, { key = "e" } },
    ["í"] = { { key = "equal" }, { key = "i" } },
    ["ì"] = { { key = "equal", modifier = "lshift" }, { key = "i" } },
    ["î"] = { { key = "tilde" }, { key = "i" } },
    ["ó"] = { { key = "equal" }, { key = "o" } },
    ["ò"] = { { key = "equal", modifier = "lshift" }, { key = "o" } },
    ["ô"] = { { key = "tilde" }, { key = "o" } },
    ["ú"] = { { key = "equal" }, { key = "u" } },
    ["ù"] = { { key = "equal", modifier = "lshift" }, { key = "u" } },
    ["û"] = { { key = "tilde" }, { key = "u" } }
}

tl.stringPresets.logitechKeyNames = { "tilde", "minus", "equal", "lbracket", "rbracket", "backslash", "capslock", "semicolon", "quote", "comma", "period", "slash", "escape", "enter", "tab", "spacebar", "up", "left", "down", "right", "backspace", "lshift", "rshift", "lctrl", "rctrl", "lalt", "ralt", "lgui", "rgui", "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15", "f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23", "f24", "delete", "home", "insert", "pause", "pagedown", "pageup", "printscreen", "scrolllock", "appkey", "non_us_slash", "numlock", "end", "num0", "num1", "num2", "num3", "num4", "num5", "num6", "num7", "num8", "num9", "numslash", "numminus", "numplus", "numenter", "numperiod" }